---
name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: 2.2.7
slug: "smart_hub"
arch:
  - aarch64
ports:
  7777/udp: 7777
startup: services
init: false
full_access: false
hassio_api: true
homeassistant_api: true
host_network: true
map: [addon_config:rw]
devices: ["dev/serial0"]
uart: true
devicetree: true
ingress: true
ingress_stream : true
panel_title: Smart Configurator
panel_icon: hbt:habitron-logo
panel_admin: true
image: "ghcr.io/dneprojects/smart_hub/{arch}"
